### ISSUE TITLE
Module fp.fp is not found in python3 libaray

### ISSUE THREAD

**Issue by HarizDharma** [amineKammah/web-bot#1]
![Screenshot-20210227154144-1263x594](https://user-images.githubusercontent.com/58357619/109382324-55282a80-7912-11eb-9f94-0b55cc20f02c.png)

Please Help
I want to run and stuck in this process, but i try to install fp.fp and in distibution dont have this module

Thanks

**Comment by amineKammah** [comment]
Try pulling the latest version and should be good to go!

**Comment by HarizDharma** [comment]
> Try pulling the latest version and should be good to go!

![Screenshot-20210227192135-846x432](https://user-images.githubusercontent.com/58357619/109386974-05a52700-7931-11eb-92d0-cb59eac45c8b.png)


WOw Thanks Work , but got this error message 

i hope fine now

**Comment by HarizDharma** [comment]
this tools work and i closed this issue , i try this tools.

**Comment by HarizDharma** [comment]
Closed !
